spring:
  application:
    name: order-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

---
spring:
  profiles: order1
server:
  port: 8005
  
---
spring:
  profiles: order2
server:
  port: 8006


